cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://canteen-web-mu.vercel.app"
    - "https://canteen-admin-orcin.vercel.app"

backend:
  port: 3002

admin:
  url: "http://localhost:5000"
