cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://canteenz.vercel.app"
    - "https://admin-canteenz.vercel.app"

backend:
  port: 3002

admin:
  url: "http://localhost:5000"
